name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build & Test
    strategy:
      matrix:
        go: [1.11,1.12,1.13,1.14]

    runs-on: ubuntu-latest

    container:
        image: golang:${{ matrix.go }}-stretch

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run
      run: |
        mkdir -p /tmp/go/src/github.com/magejiCoder
        mv . /tmp/go/src/github.com/magejiCoder/issue-1094
        go run /tmp/go/src/github.com/magejiCoder/issue-1094/main.go
      env:
        GOPATH: /tmp/go
        GO111MODULE: off
